### PR TITLE
Now it is possible to use random pages with syntax shortcuts

### PR DESCRIPTION
**Pull request by Zacharia2**
use：<randompage_syntax>Random Page</randompage_syntax>

@raster hi，I've written a syntax shortcut for it to be used quickly in the sidebar. If you have time you can take a look at it.

It is better to refresh the dokuwiki\data\index\page.idx file。This will not show the deleted pages

Perhaps it would be more accurate and faster to read the files in the dokuwiki\data\pages folder to generate the list.

### CODE REVIEW

**Comment by raster** [comment]
Thanks! I will try to review this and merge it.

**Review by raster — APPROVED** [review]

**Comment by Zacharia2** [comment]
The dokuwiki plugin page remember to modify it, if you still maintain it.

**Comment by Zacharia2** [comment]
nsrandompage is a random page function in the namespace written by the author of the other branch, and I didn't add the syntax because I didn't know if it would be useful

**Comment by Zacharia2** [comment]
Deleted pages
This plugin is not usable for me as it returns deleted pages. I've tried on 3 DokuWiki installs and the bug is always there. Does anyone has found a solution ? — Laynee 2009/06/17 22:52

Just recreate the page index ( re run ../bin/indexer.php) — ueli 2009-okt-29 22:18

**Comment by raster** [comment]
It's probably best if I do not maintain it... I would love for someone else to take it over. (I really don't manage any active dokuwiki sites anymore, which makes testing things a little difficult.)

Maybe this one will work: https://github.com/DanDude0/DokuWiki-randompage

**Comment by Zacharia2** [comment]
Thank you. If you no longer wish to maintain it, please forgive me, I think you can transfer this warehouse to me, I am more than happy to do it.

**Comment by Zacharia2** [comment]
Okay, thank you.

**Pull request closed without merging**
